name: tests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ "{{" }} github.workflow {{ "}}" }}-${{ "{{" }} github.event.pull_request.number || github.ref {{ "}}" }}
  cancel-in-progress: true

{%- if cookiecutter.crds_observatory != 'none' %}
env:
  CRDS_PATH: /tmp/data/crds_cache
  CRDS_OBSERVATORY: {{ cookiecutter.crds_observatory }}
  CRDS_SERVER_URL: https://{{ cookiecutter.crds_observatory }}-crds.stsci.edu
  CRDS_CLIENT_RETRY_COUNT: 3
  CRDS_CLIENT_RETRY_DELAY_SECONDS: 20
{%- endif %}

jobs:
{%- if cookiecutter.task_runner != 'tox' %}
  supported-pythons:
    runs-on: ubuntu-latest
    steps:
      - id: supported-pythons
        uses: zacharyburnett/supported-pythons@9186be100e84431de457f333fe8f793f079f5b66 # 2.0.3
        with:
          package: ${{ "{{" }} github.repository {{ "}}" }}
          package-ref: ${{ "{{" }} github.ref || github.sha {{ "}}" }}
    outputs:
      versions: ${{ "{{" }} steps.supported-pythons.outputs.versions {{ "}}" }}
{%- endif %}
{%- if cookiecutter.crds_observatory != 'none' %}
  crds:
    runs-on: ubuntu-latest
    steps:
      - id: latest-context
        run: >
          echo latest-context=$(
            curl -s -X POST -d '{"jsonrpc": "1.0", "method": "get_default_context", "params": ["${{ "{{" }} env.CRDS_OBSERVATORY {{ "}}" }}", "latest"], "id": 1}' ${{ "{{" }} env.CRDS_SERVER_URL {{ "}}" }}/json/ --retry 8 --connect-timeout 10 |
            python -c "import sys, json; print(json.load(sys.stdin)['result'])"
          ) >> $GITHUB_OUTPUT
    outputs:
      latest-context: ${{ "{{" }} steps.latest-context.outputs.latest-context {{ "}}" }}
{%- endif %}
  test:
{%- if cookiecutter.task_runner != 'tox' or cookiecutter.crds_observatory != 'none' %}
    needs:
{%- if cookiecutter.task_runner != 'tox' %}
      - supported-pythons
{%- endif %}
{%- if cookiecutter.crds_observatory != 'none' %}
      - crds
{%- endif %}
{%- endif %}
{%- if cookiecutter.task_runner != 'tox' %}
    strategy:
      fail-fast: false
      matrix:
        runs-on: ["ubuntu-latest"]
{%- if cookiecutter.task_runner == 'none' %}
        python-version: ${{ "{{" }} fromJSON(needs.supported-pythons.outputs.versions) {{ "}}" }}
{%- endif %}
        coverage: [false]
        include:
          - runs-on: "ubuntu-latest"
{%- if cookiecutter.task_runner == 'none' %}
            python-version: "3"
{%- endif %}
            coverage: true
          - runs-on: "macos-latest"
{%- if cookiecutter.task_runner == 'none' %}
            python-version: "3"
{%- endif %}
    name: run tests (Python ${{ "{{" }} {%- if cookiecutter.task_runner == 'nox' -%}needs.supported-pythons.outputs.versions{%- else -%}matrix.python-version{%- endif -%} {{ "}}" }}, ${{ "{{" }} matrix.runs-on {{ "}}" }})
    runs-on: ${{ "{{" }} matrix.runs-on {{ "}}" }}
{%- if cookiecutter.crds_observatory != 'none' %}
    env:
      CRDS_CONTEXT: ${{ "{{" }} needs.crds.outputs.latest-context {{ "}}" }}
{%- endif %}
    steps:
{%- if cookiecutter.crds_observatory != 'none' %}
      - name: cache CRDS reference files retrieved during testing
        uses: actions/cache@v5
        with:
          path: ${{ "{{" }} env.CRDS_PATH {{ "}}" }}
          key: ${{ "{{" }} env.CRDS_CONTEXT {{ "}}" }}
{%- endif %}
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
{%- if cookiecutter.task_runner == 'none' %}
        with:
          python-version: ${{ "{{" }} matrix.python-version {{ "}}" }}
      - run: pip install ".[test]" ${{ "{{" }} matrix.coverage && 'coverage pytest-cov' || '' {{ "}}" }}
      - run: pytest ${{ "{{" }} matrix.coverage && '--cov' || '' {{ "}}" }}
{%- elif cookiecutter.task_runner == 'nox' %}
      - uses: wntrblm/nox@5a277b752f6094150e25237d47c34168e2b7526e # 2026.02.09
        with:
            python-versions: ${{ "{{" }} runner.os != 'macOS' && needs.supported-pythons.outputs.versions || '3' {{ "}}" }}
            session: test${{ "{{" }} matrix.coverage && '_with_coverage' || '' {{ "}}" }}
{%- endif %}
      - if: matrix.coverage
        name: report coverage to summary
        run: |
          coverage combine
          echo '## Coverage Report' >> $GITHUB_STEP_SUMMARY
          coverage report -i -m --format=markdown | tee -a $GITHUB_STEP_SUMMARY
{%- elif cookiecutter.task_runner == 'tox' %}
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v2
    with:
{%- if cookiecutter.crds_observatory != 'none' %}
      setenv: |
        CRDS_PATH: ${{ "{{" }} env.CRDS_PATH {{ "}}" }}
        CRDS_SERVER_URL: ${{ "{{" }} env.CRDS_SERVER_URL {{ "}}" }}
        CRDS_CONTEXT: ${{ "{{" }} needs.crds.outputs.latest-context {{ "}}" }}
        CRDS_CLIENT_RETRY_COUNT: ${{ "{{" }} env.CRDS_CLIENT_RETRY_COUNT {{ "}}" }}
        CRDS_CLIENT_RETRY_DELAY_SECONDS: ${{ "{{" }} env.CRDS_CLIENT_RETRY_DELAY_SECONDS {{ "}}" }}
      cache-path: ${{ "{{" }} env.CRDS_PATH {{ "}}" }}
      cache-key: crds-${{ "{{" }} needs.crds.outputs.latest-context {{ "}}" }}
{%- endif %}
      envs: |
        - linux: py3-cov
          pytest-results-summary: true
          coverage: github
        - macos: py3
      fill: true
      fill_platforms: linux
      artifact-path: |
        results.xml
{%- endif %}
